//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.01 at 06:08:39 AM CDT 
//


package com.bioscope.domain.userRatingService;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bioscope.domain.userRatingService package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Movie_QNAME = new QName("http://webservices.samples.blog.com", "Movie");
    private final static QName _User_QNAME = new QName("http://webservices.samples.blog.com/user", "User");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bioscope.domain.userRatingService
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserRatingRequest }
     * 
     */
    public UserRatingRequest createUserRatingRequest() {
        return new UserRatingRequest();
    }

    /**
     * Create an instance of {@link UserRatingResponse }
     * 
     */
    public UserRatingResponse createUserRatingResponse() {
        return new UserRatingResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link ListMovies }
     * 
     */
    public ListMovies createListMovies() {
        return new ListMovies();
    }

    /**
     * Create an instance of {@link Movie }
     * 
     */
    public Movie createMovie() {
        return new Movie();
    }

    /**
     * Create an instance of {@link ListReviews }
     * 
     */
    public ListReviews createListReviews() {
        return new ListReviews();
    }

    /**
     * Create an instance of {@link Review }
     * 
     */
    public Review createReview() {
        return new Review();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Movie }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.samples.blog.com", name = "Movie")
    public JAXBElement<Movie> createMovie(Movie value) {
        return new JAXBElement<Movie>(_Movie_QNAME, Movie.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.samples.blog.com/user", name = "User")
    public JAXBElement<User> createUser(User value) {
        return new JAXBElement<User>(_User_QNAME, User.class, null, value);
    }

}
