//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.26 at 09:44:14 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.samples.blog.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bioscope.domain;
