//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.26 at 09:44:14 PM CDT 
//


package com.bioscope.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for User complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="User">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="moviesWatched" type="{http://webservices.samples.blog.com/user}listMovies"/>
 *         &lt;element name="moviesRated" type="{http://webservices.samples.blog.com/user}listMovies"/>
 *         &lt;element name="moviesWatchLater" type="{http://webservices.samples.blog.com/user}listMovies"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "User", namespace = "http://webservices.samples.blog.com/user", propOrder = {
    "id",
    "userName",
    "moviesWatched",
    "moviesRated",
    "moviesWatchLater"
})
public class User {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    protected ListMovies moviesWatched;
    @XmlElement(required = true)
    protected ListMovies moviesRated;
    @XmlElement(required = true)
    protected ListMovies moviesWatchLater;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the moviesWatched property.
     * 
     * @return
     *     possible object is
     *     {@link ListMovies }
     *     
     */
    public ListMovies getMoviesWatched() {
        return moviesWatched;
    }

    /**
     * Sets the value of the moviesWatched property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListMovies }
     *     
     */
    public void setMoviesWatched(ListMovies value) {
        this.moviesWatched = value;
    }

    /**
     * Gets the value of the moviesRated property.
     * 
     * @return
     *     possible object is
     *     {@link ListMovies }
     *     
     */
    public ListMovies getMoviesRated() {
        return moviesRated;
    }

    /**
     * Sets the value of the moviesRated property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListMovies }
     *     
     */
    public void setMoviesRated(ListMovies value) {
        this.moviesRated = value;
    }

    /**
     * Gets the value of the moviesWatchLater property.
     * 
     * @return
     *     possible object is
     *     {@link ListMovies }
     *     
     */
    public ListMovies getMoviesWatchLater() {
        return moviesWatchLater;
    }

    /**
     * Sets the value of the moviesWatchLater property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListMovies }
     *     
     */
    public void setMoviesWatchLater(ListMovies value) {
        this.moviesWatchLater = value;
    }

}
